# Generated by Django 5.2.6 on 2025-09-16 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='language',
            field=models.TextField(blank=True, choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('ja', 'Japan'), ('zh', 'Chinese'), ('hi', 'Hindu'), ('ru', 'Russian'), ('pt', 'portugese'), ('it', 'Italian'), ('ko', 'Korean'), ('sh', 'Swahili')], default='en', help_text='Please provide a language for the book', max_length=3),
        ),
    ]
